---
openapi: 3.0.0
info:
  title: Web API Interface
  description: |
    Created by Wenlong Lu.
  contact:
    email: 20091572@mail.wit.ie
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

